function createfigure(x1, YMatrix1, YMatrix2)
%CREATEFIGURE(X1,YMATRIX1,YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 16-Feb-2013 22:36:11

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1,'YGrid','on','XGrid','on');
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 200000]);
box(subplot1,'on');
hold(subplot1,'all');

% Create title
title('Plot of training and test errors for lambda = 0');

% Create multiple lines using matrix input to plot
plot1 = plot(x1,YMatrix1,'Parent',subplot1,'LineWidth',2);
set(plot1(1),'DisplayName','Training Error');
set(plot1(2),'LineStyle','--','DisplayName','Test Error');

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'all');

% Create title
title('Plot of training and test errors for lambda = 0.2');

% Create xlabel
xlabel('k');

% Create ylabel
ylabel('Error');

% Create multiple lines using matrix input to plot
plot2 = plot(x1,YMatrix2,'Parent',subplot2,'LineWidth',2);
set(plot2(1),'DisplayName','Training Error');
set(plot2(2),'LineStyle','--','DisplayName','Test Error');

% Create legend
legend(subplot1,'show');

% Create legend
legend1 = legend(subplot2,'show');
set(legend1,...
    'Position',[0.733462151435362 0.401567320522952 0.180418804235839 0.0549852395771166]);

